<a href="https://colab.research.google.com/github/AudryBarimbane/numpy_notebook_exercises/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [ ]:
a[2] = 10

In [ ]:
a

array([ 1,  2, 10,  5,  7, 12])

In [ ]:
a[2] = 10

In [ ]:
a

array([ 1,  2, 10,  5,  7, 12])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
 n = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
 

In [ ]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
n[0]

array([ 1, 20,  3])

In [ ]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
n[:,2]

array([3, 6, 1])

In [ ]:
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
n[:,2] = [0,1,2]

In [ ]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

**Randomly generated arrays**

In [ ]:
np.random.rand(5,2)

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

In [ ]:
np.random.seed(3)
np.random.rand(5,2)

array([[0.5507979 , 0.70814782],
       [0.29090474, 0.51082761],
       [0.89294695, 0.89629309],
       [0.12558531, 0.20724288],
       [0.0514672 , 0.44080984]])

In [ ]:
np.random.seed(3)
np.random.randn(5,2)

array([[ 1.78862847,  0.43650985],
       [ 0.09649747, -1.8634927 ],
       [-0.2773882 , -0.35475898],
       [-0.08274148, -0.62700068],
       [-0.04381817, -0.47721803]])

In [ ]:
np.random.seed(2)
np.random.randint(low=2,high=100,size=(5,2))

array([[42, 17],
       [74, 24],
       [45, 84],
       [77,  9],
       [36, 51]])

# **Element-wise operations**

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
a+1

array([1, 2, 3, 4, 5])

In [ ]:
a*2

array([0, 2, 4, 6, 8])

In [ ]:
a/100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [ ]:
b = (10+(a*2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

**Comparison operations** 

In [ ]:
a >= 2

array([False, False,  True,  True,  True])

In [ ]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
a > b

array([False, False,  True,  True,  True])

In [ ]:
a[a > b]

array([2, 3, 4])

**Summarizing operations**

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a.min()

0

In [ ]:
a.max()

4

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.0

In [ ]:
a.std()

1.4142135623730951

In [ ]:
n.min()

0

In [ ]:
n.max()

20